### ISSUE TITLE
Default rule "*" includes everything else. Fails to validate bogus .bad tld  as a public suffix.

### ISSUE THREAD

**Issue by fooinha** [whois-server-list/public-suffix-list#5]
Hi, 

Sorry if I am not seeing this correctly, but by having the default rule ("*") aren't we allowing any dummy or unknown .tld to be considered as a suffix? (public)
 
Is this library also supposed to be a public suffix validator? 
If so, shouldn't we use instead the "!*" rule (with exception) in order to match non valid suffixes? 
  
PublicSuffixListFactory.java#L128

**Comment by malkusch** [comment]
>  but by having the default rule ("*") aren't we allowing any dummy or unknown .tld to be considered as a suffix?

Well, that's how the [PSL](https://publicsuffix.org/list/) is defined:

>  If no rules match, the prevailing rule is "*". 

I do understand that any TLD is then considered a public suffix.

> Is this library also supposed to be a public suffix validator? 

The questions this library can answer are:

- [isPublicSuffix()](http://whois-server-list.github.io/public-suffix-list/apidocs/de/malkusch/whoisServerList/publicSuffixList/PublicSuffixList.html#isPublicSuffix%28java.lang.String%29)
- [isRegistrable()](http://whois-server-list.github.io/public-suffix-list/apidocs/de/malkusch/whoisServerList/publicSuffixList/PublicSuffixList.html#isRegistrable%28java.lang.String%29)

Yes, it is then. But I guess if you are not happy with that behaviour you should knock at PSL directly.
