### ISSUE TITLE
unable to load public suffix list from location outside of classpath

### ISSUE THREAD

**Issue by jgangemi** [whois-server-list/public-suffix-list#6]
i would like to be able to load the public suffix list from an external location on disk and not the classpath but this is not currently possible b/c the underlying code is using `getResourceAsStream` to load the file.

can this be changed and/or enhanced to support my use case? 

the simplest thing to do would be to check if the `InputStream` returned from the call is `null` and if yes, try loading the file using a `FileInputStream`.

i'd be happy to submit a pull request for this.

**Comment by malkusch** [comment]
I'll have a look at it. In the mean time you could change your class path to include the file.

**Comment by malkusch** [comment]
Added [`PublicSuffixListFactory::build(InputStream)`](http://whois-server-list.github.io/public-suffix-list/apidocs/de/malkusch/whoisServerList/publicSuffixList/PublicSuffixListFactory.html#build-java.io.InputStream-) in [2.1.0](https://github.com/whois-server-list/public-suffix-list/releases/tag/public-suffix-list-2.1.0).

**Comment by jgangemi** [comment]
awesome, thanks for this!
